[technote]
id = "SITCOMTN-084"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-084.lsst.io/"
github_url = "https://github.com/lsst-sitcom/sitcomtn-084"
github_default_branch = "main"
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[[technote.authors]]
name = {given = "Dominique", family = "Boutigny"}
internal_id = "boutignyd"
orcid = "https://orcid.org/0000-0003-4887-2150"
[[technote.authors.affiliations]]
name = "Université Grenoble-Alpes"
internal_id = "LAPP"
address = "Université Savoie Mont Blanc, CNRS/IN2P3 Laboratoire d'Annecy-le-Vieux de Physique des Particules, 9 Chemin de Bellevue – BP 110, F-74940 Annecy-le-Vieux Cedex, France"

[[technote.authors]]
name = {given = "Craig S.", family = "Lage"}
internal_id = "lagecs"
[[technote.authors.affiliations]]
name = "Physics Department"
internal_id = "UCDavis"
address = "University of California, One Shields Avenue, Davis, CA 95616, USA"

[[technote.authors]]
name = {given = "Joaquin", family = "Hernandez"}

[[technote.authors]]
name = {given = "Andrea", family = "Jeremie"}

[[technote.authors]]
name = {given = "HyeYun", family = "Park"}